#!/bin/bash

parent_dir_1=$(dirname "$2")
base_dir_1=$(basename "$2")
echo Logging to $1 and compressing...
ssh $1 "cd \"$parent_dir_1\" && tar -czvf tarball.tar.gz \"$base_dir_1\""
echo Copying to host...
scp $1:$parent_dir_1/tarball.tar.gz .
echo Removing compressed file from $1...
ssh $1 "cd \"$parent_dir_1\" && rm -rf tarball.tar.gz"
echo Copying to $3...
scp tarball.tar.gz $3:$4
echo Remove compressed file from host...
rm -rf tarball.tar.gz
echo Extracting and removing compressed file from $3...
ssh $3 "cd \"$4\" && tar -xvzf tarball.tar.gz && rm -rf tarball.tar.gz"
